# Generated by Django 3.2.4 on 2021-06-23 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat_app', '0002_auto_20210623_0856'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='room',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
