# Generated by Django 3.2.4 on 2021-06-23 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat_app', '0003_alter_room_room'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='room',
            field=models.CharField(blank=True, max_length=255, unique=True),
        ),
    ]
